给定一个向量，让向量中每一个数乘以2
a = (0,1,2)

In [1]:
n = 10
L = [i for i in range(n)]

In [2]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
A = []
for e in L:
    A.append(2*e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [4]:
%%time
A = [2*e for e in L]

Wall time: 0 ns


In [5]:
import numpy as np
L = np.arange(n)

In [6]:
%%time
A = [2*e for e in L]

Wall time: 997 µs


In [7]:
%%time
A = 2 * L

Wall time: 1.99 ms


In [8]:
A

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Universal Functions

In [9]:
X = np.arange(1,16).reshape((3,5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [11]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [13]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [14]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [15]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [16]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [17]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [19]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [20]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [21]:
3**X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [22]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

### 矩阵运算

In [24]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [25]:
B = np.full((2,2), 10)
B

array([[10, 10],
       [10, 10]])

In [26]:
A + B

array([[10, 11],
       [12, 13]])

In [27]:
A * B

array([[ 0, 10],
       [20, 30]])

In [28]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [29]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [30]:
A.T

array([[0, 2],
       [1, 3]])

In [31]:
C = np.full((3,3),10)

In [32]:
C

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### 向量和矩阵的运算

In [33]:
v = np.array([1,2])

In [34]:
A

array([[0, 1],
       [2, 3]])

In [35]:
v + A

array([[1, 3],
       [3, 5]])

In [37]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [38]:
A.shape[0]

2

In [39]:
np.vstack([v]*2)

array([[1, 2],
       [1, 2]])

In [40]:
np.vstack([v] * A.shape[0]) + A 

array([[1, 3],
       [3, 5]])

In [41]:
np.tile(v, (2,1))

array([[1, 2],
       [1, 2]])

In [42]:
np.tile(v, (2,1)) + A

array([[1, 3],
       [3, 5]])

In [43]:
v * A

array([[0, 2],
       [2, 6]])

In [44]:
v.dot(A)

array([4, 7])

In [45]:
A.dot(v)

array([2, 8])

### 矩阵的逆

In [46]:
A

array([[0, 1],
       [2, 3]])

In [48]:
invA = np.linalg.inv(A)

In [49]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [50]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [52]:
X = np.arange(16).reshape((2,8))
pinvX = np.linalg.pinv(X)

In [53]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.91433544e-16],
       [ 1.33226763e-15,  1.00000000e+00]])